Controllers/EditProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using Health_Insurance.Models;

namespace Health_Insurance.Controllers
{


    public class EditProfileController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditProfileController(ModelContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null || _context.Useraccounts == null)
            {
                return NotFound();
            }

            var useraccount = await _context.Useraccounts.FindAsync(id);
            if (useraccount == null)
            {
                return NotFound();
            }
            ViewData["RolesId"] = new SelectList(_context.Roles, "Id", "Id", useraccount.RolesId);
            return View(useraccount);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Id,FullName,Username,Passwd,Email,PhoneNumber,Address,RolesId,Imagepath,ImageFile")] Useraccount useraccount)
        {
            HttpContext.Session.SetString("Fullname", useraccount.FullName);
            HttpContext.Session.SetString("Address", useraccount.Address);
            HttpContext.Session.SetInt32("UserId", (int)useraccount.Id);
            HttpContext.Session.SetString("ImagePath", useraccount.Imagepath);
            HttpContext.Session.SetString("Username", useraccount.Username);
            HttpContext.Session.SetString("PhoneNumber", useraccount.PhoneNumber);
            HttpContext.Session.SetString("Passwd", useraccount.Passwd);
            HttpContext.Session.SetString("Email", useraccount.Email);



            if (id != useraccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (useraccount.ImageFile != null)
                    {
                        string WWWRootPath = webHostEnvironment.WebRootPath;
                        string fileName = Guid.NewGuid().ToString() + useraccount.ImageFile.FileName;
                        string path = Path.Combine(WWWRootPath + "/Images/" + fileName);


                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await useraccount.ImageFile.CopyToAsync(fileStream);
                        }

                        useraccount.Imagepath = fileName;
                    }
                  
                    _context.Update(useraccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UseraccountExists(useraccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RolesId"] = new SelectList(_context.Roles, "Id", "Id", useraccount.RolesId);
            return View(useraccount);
        }

        private bool UseraccountExists(decimal id)
        {
            return _context.Useraccounts.Any(e => e.Id == id);
        }


    }
}

Views/EditProfile/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Health_Insurance.Models.Useraccount

@{
    Layout = "@ViewBag.Layout";
}

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="EditProfile" asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Passwd" class="control-label"></label>
                <input asp-for="Passwd" class="form-control" />
                <span asp-validation-for="Passwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RolesId" class="control-label"></label>
                <select asp-for="RolesId" class="form-control" asp-items="ViewBag.RolesId"></select>
                <span asp-validation-for="RolesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagepath" hidden class="control-label"></label>
                <input asp-for="Imagepath" class="form-control" />
                <span asp-validation-for="Imagepath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>